version: '3.9'

services:
    serve:
        image: tccoin/klog2.0:latest
        working_dir: "/app"
        volumes:
            - ./settings.js:/app/settings.js
            - ./storage:/app/storage
            - /etc/letsencrypt/archive/klog.app:/app/cert
        entrypoint: [ "yarn", "run", "serve" ]
        expose:
            - 3000
            - 3001
        restart: always
        depends_on:
            - watchtower
    debug:
        image: tccoin/klog2.0:latest
        working_dir: "/app"
        volumes:
            - ./settings.js:/app/settings.js
            - ./storage:/app/storage
            - /etc/letsencrypt/live/klog.app:/app/cert
        entrypoint: [ "bash" ]
        expose:
            - 80:3000
        restart: always
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
